--------------------------------------------------------
--  File created - Tuesday-December-31-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ASSESSMENT_MASTER
--------------------------------------------------------

  CREATE TABLE "ASSESSMENT_MASTER" 
   (	"ASSESSMENT_ID" NUMBER(10,0), 
	"CANDIDATE_ID" NUMBER(*,0), 
	"HR_ROUND_RATING" NUMBER(10,0), 
	"TECHNICAL_RATING" NUMBER(10,0), 
	"COMMUNICATION_RATING" NUMBER(10,0), 
	"GD_ROUND_RATING" NUMBER(10,0), 
	"APTITUTE_ROUND_RATING" NUMBER(10,0), 
	"OVERALL_ROUND_RATING" NUMBER(10,0), 
	"STATUS" VARCHAR2(30 BYTE), 
	"CREATED_ON" TIMESTAMP (6), 
	"UPDATED_ON" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into ASSESSMENT_MASTER
SET DEFINE OFF;
Insert into ASSESSMENT_MASTER (ASSESSMENT_ID,CANDIDATE_ID,HR_ROUND_RATING,TECHNICAL_RATING,COMMUNICATION_RATING,GD_ROUND_RATING,APTITUTE_ROUND_RATING,OVERALL_ROUND_RATING,STATUS,CREATED_ON,UPDATED_ON) values (501,1001,3,5,4,3,4,4,'not selected',to_timestamp('12-FEB-16 11.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('12-JAN-16 05.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into ASSESSMENT_MASTER (ASSESSMENT_ID,CANDIDATE_ID,HR_ROUND_RATING,TECHNICAL_RATING,COMMUNICATION_RATING,GD_ROUND_RATING,APTITUTE_ROUND_RATING,OVERALL_ROUND_RATING,STATUS,CREATED_ON,UPDATED_ON) values (1000,500,6,5,4,2,2,5,'selected',to_timestamp('12-FEB-16 11.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('12-JAN-16 05.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into ASSESSMENT_MASTER (ASSESSMENT_ID,CANDIDATE_ID,HR_ROUND_RATING,TECHNICAL_RATING,COMMUNICATION_RATING,GD_ROUND_RATING,APTITUTE_ROUND_RATING,OVERALL_ROUND_RATING,STATUS,CREATED_ON,UPDATED_ON) values (1001,501,5,5,4,4,4,4,'selected',to_timestamp('12-FEB-16 11.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('12-JAN-16 05.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into ASSESSMENT_MASTER (ASSESSMENT_ID,CANDIDATE_ID,HR_ROUND_RATING,TECHNICAL_RATING,COMMUNICATION_RATING,GD_ROUND_RATING,APTITUTE_ROUND_RATING,OVERALL_ROUND_RATING,STATUS,CREATED_ON,UPDATED_ON) values (1002,502,1,2,2,1,3,5,'not selected',to_timestamp('12-FEB-16 11.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('12-JAN-16 05.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into ASSESSMENT_MASTER (ASSESSMENT_ID,CANDIDATE_ID,HR_ROUND_RATING,TECHNICAL_RATING,COMMUNICATION_RATING,GD_ROUND_RATING,APTITUTE_ROUND_RATING,OVERALL_ROUND_RATING,STATUS,CREATED_ON,UPDATED_ON) values (1003,503,5,1,2,2,2,4,'not selected',to_timestamp('12-FEB-16 11.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('12-JAN-16 05.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into ASSESSMENT_MASTER (ASSESSMENT_ID,CANDIDATE_ID,HR_ROUND_RATING,TECHNICAL_RATING,COMMUNICATION_RATING,GD_ROUND_RATING,APTITUTE_ROUND_RATING,OVERALL_ROUND_RATING,STATUS,CREATED_ON,UPDATED_ON) values (1004,504,3,5,5,1,1,4,' not selected',to_timestamp('12-FEB-16 11.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('12-JAN-16 05.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
--------------------------------------------------------
--  DDL for Index SYS_C007311
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007311" ON "ASSESSMENT_MASTER" ("ASSESSMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger ASSESSMENT_MASTER_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ASSESSMENT_MASTER_TRG" 
BEFORE INSERT ON ASSESSMENT_MASTER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ASSESSMENT_ID IS NULL THEN
      SELECT ASSESSMENT_MASTER_SEQ.NEXTVAL INTO :NEW.ASSESSMENT_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ASSESSMENT_MASTER_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table ASSESSMENT_MASTER
--------------------------------------------------------

  ALTER TABLE "ASSESSMENT_MASTER" ADD PRIMARY KEY ("ASSESSMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ASSESSMENT_MASTER" MODIFY ("UPDATED_ON" NOT NULL ENABLE);
  ALTER TABLE "ASSESSMENT_MASTER" MODIFY ("CREATED_ON" NOT NULL ENABLE);
  ALTER TABLE "ASSESSMENT_MASTER" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "ASSESSMENT_MASTER" MODIFY ("OVERALL_ROUND_RATING" NOT NULL ENABLE);
  ALTER TABLE "ASSESSMENT_MASTER" MODIFY ("APTITUTE_ROUND_RATING" NOT NULL ENABLE);
  ALTER TABLE "ASSESSMENT_MASTER" MODIFY ("GD_ROUND_RATING" NOT NULL ENABLE);
  ALTER TABLE "ASSESSMENT_MASTER" MODIFY ("COMMUNICATION_RATING" NOT NULL ENABLE);
  ALTER TABLE "ASSESSMENT_MASTER" MODIFY ("TECHNICAL_RATING" NOT NULL ENABLE);
  ALTER TABLE "ASSESSMENT_MASTER" MODIFY ("HR_ROUND_RATING" NOT NULL ENABLE);
  ALTER TABLE "ASSESSMENT_MASTER" MODIFY ("CANDIDATE_ID" NOT NULL ENABLE);
