--------------------------------------------------------
--  File created - Tuesday-December-31-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CANDIDATE_MASTER
--------------------------------------------------------

  CREATE TABLE "CANDIDATE_MASTER" 
   (	"CANDIDATE_ID" NUMBER(10,0), 
	"NAME" VARCHAR2(30 BYTE), 
	"LOCATION" VARCHAR2(30 BYTE), 
	"CONTACT" NUMBER(15,0), 
	"EMAIL" VARCHAR2(40 BYTE), 
	"QUALIFICATION" VARCHAR2(40 BYTE), 
	"SKILLS" VARCHAR2(50 BYTE), 
	"CERTIFICATION" VARCHAR2(40 BYTE), 
	"STATUS" VARCHAR2(30 BYTE), 
	"CREATED_ON" TIMESTAMP (6), 
	"UPDATED_ON" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into CANDIDATE_MASTER
SET DEFINE OFF;
Insert into CANDIDATE_MASTER (CANDIDATE_ID,NAME,LOCATION,CONTACT,EMAIL,QUALIFICATION,SKILLS,CERTIFICATION,STATUS,CREATED_ON,UPDATED_ON) values (1001,'rupesh','mumbai',8898776767,'xyz@gmail.com','BE','.Net','java certified','selected',to_timestamp('12-FEB-16 11.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('12-JAN-16 05.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into CANDIDATE_MASTER (CANDIDATE_ID,NAME,LOCATION,CONTACT,EMAIL,QUALIFICATION,SKILLS,CERTIFICATION,STATUS,CREATED_ON,UPDATED_ON) values (500,'sweta','mumbai',1234567890,'abc@gmail.com','BE','JAVA','java certified','selected',to_timestamp('15-NOV-19 11.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('15-NOV-19 05.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into CANDIDATE_MASTER (CANDIDATE_ID,NAME,LOCATION,CONTACT,EMAIL,QUALIFICATION,SKILLS,CERTIFICATION,STATUS,CREATED_ON,UPDATED_ON) values (501,'chandan','thane',1298463740,'xyz@gmail.com','mca','.net','java certified','selected',to_timestamp('12-NOV-19 11.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('12-NOV-19 05.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into CANDIDATE_MASTER (CANDIDATE_ID,NAME,LOCATION,CONTACT,EMAIL,QUALIFICATION,SKILLS,CERTIFICATION,STATUS,CREATED_ON,UPDATED_ON) values (502,'siddhesh','goa',4653837253,'pqr@gmail.com','be','.java','java certified','selected',to_timestamp('24-NOV-19 11.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('24-NOV-19 05.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into CANDIDATE_MASTER (CANDIDATE_ID,NAME,LOCATION,CONTACT,EMAIL,QUALIFICATION,SKILLS,CERTIFICATION,STATUS,CREATED_ON,UPDATED_ON) values (503,'vaishnavi','alibaug',1736458974,'vai@gmail.com','be','java','java certified','selected',to_timestamp('12-NOV-19 11.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('12-NOV-19 05.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into CANDIDATE_MASTER (CANDIDATE_ID,NAME,LOCATION,CONTACT,EMAIL,QUALIFICATION,SKILLS,CERTIFICATION,STATUS,CREATED_ON,UPDATED_ON) values (504,'rupesh','mumbai',8898776767,'xyz@gmail.com','BE','.Net','java certified','selected',to_timestamp('12-FEB-16 11.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('12-JAN-16 05.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
--------------------------------------------------------
--  DDL for Index SYS_C007300
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007300" ON "CANDIDATE_MASTER" ("CANDIDATE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CANDIDATE_MASTER
--------------------------------------------------------

  ALTER TABLE "CANDIDATE_MASTER" ADD PRIMARY KEY ("CANDIDATE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CANDIDATE_MASTER" MODIFY ("UPDATED_ON" NOT NULL ENABLE);
  ALTER TABLE "CANDIDATE_MASTER" MODIFY ("CREATED_ON" NOT NULL ENABLE);
  ALTER TABLE "CANDIDATE_MASTER" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "CANDIDATE_MASTER" MODIFY ("CERTIFICATION" NOT NULL ENABLE);
  ALTER TABLE "CANDIDATE_MASTER" MODIFY ("SKILLS" NOT NULL ENABLE);
  ALTER TABLE "CANDIDATE_MASTER" MODIFY ("QUALIFICATION" NOT NULL ENABLE);
  ALTER TABLE "CANDIDATE_MASTER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "CANDIDATE_MASTER" MODIFY ("CONTACT" NOT NULL ENABLE);
  ALTER TABLE "CANDIDATE_MASTER" MODIFY ("LOCATION" NOT NULL ENABLE);
  ALTER TABLE "CANDIDATE_MASTER" MODIFY ("NAME" NOT NULL ENABLE);
