--------------------------------------------------------
--  File created - Tuesday-December-31-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EMPLOYEE_MASTER
--------------------------------------------------------

  CREATE TABLE "EMPLOYEE_MASTER" 
   (	"EMPLOYEE_ID" NUMBER(*,0), 
	"NAME" VARCHAR2(30 BYTE), 
	"CONTACT" NUMBER(15,0), 
	"DESIGNATION" VARCHAR2(30 BYTE), 
	"QUALIFICATION" VARCHAR2(40 BYTE), 
	"ADDRESS" VARCHAR2(40 BYTE), 
	"EMAIL" VARCHAR2(40 BYTE), 
	"SKILLS" VARCHAR2(50 BYTE), 
	"STATUS" VARCHAR2(30 BYTE), 
	"CREATED_ON" TIMESTAMP (6), 
	"UPDATED_ON" TIMESTAMP (6), 
	"MANAGER_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into EMPLOYEE_MASTER
SET DEFINE OFF;
Insert into EMPLOYEE_MASTER (EMPLOYEE_ID,NAME,CONTACT,DESIGNATION,QUALIFICATION,ADDRESS,EMAIL,SKILLS,STATUS,CREATED_ON,UPDATED_ON,MANAGER_ID) values (101,'rupesh',8898713725,'Developer','mca','mumbai','abc@gmail.com','java','selected',to_timestamp('12-FEB-16 11.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('12-JAN-16 05.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),null);
Insert into EMPLOYEE_MASTER (EMPLOYEE_ID,NAME,CONTACT,DESIGNATION,QUALIFICATION,ADDRESS,EMAIL,SKILLS,STATUS,CREATED_ON,UPDATED_ON,MANAGER_ID) values (102,'rupesh',8898713725,'Developer','mca','mumbai','abc@gmail.com','java','selected',to_timestamp('12-FEB-16 11.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('12-JAN-16 05.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),99);
--------------------------------------------------------
--  DDL for Trigger EMPLOYEE_MASTER_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "EMPLOYEE_MASTER_TRG" 
BEFORE INSERT ON EMPLOYEE_MASTER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.EMPLOYEE_ID IS NULL THEN
      SELECT EMPLOYEE_MASTER_SEQ.NEXTVAL INTO :NEW.EMPLOYEE_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "EMPLOYEE_MASTER_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYEE_MASTER
--------------------------------------------------------

  ALTER TABLE "EMPLOYEE_MASTER" MODIFY ("UPDATED_ON" NOT NULL ENABLE);
  ALTER TABLE "EMPLOYEE_MASTER" MODIFY ("CREATED_ON" NOT NULL ENABLE);
  ALTER TABLE "EMPLOYEE_MASTER" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "EMPLOYEE_MASTER" MODIFY ("SKILLS" NOT NULL ENABLE);
  ALTER TABLE "EMPLOYEE_MASTER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "EMPLOYEE_MASTER" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "EMPLOYEE_MASTER" MODIFY ("QUALIFICATION" NOT NULL ENABLE);
  ALTER TABLE "EMPLOYEE_MASTER" MODIFY ("DESIGNATION" NOT NULL ENABLE);
  ALTER TABLE "EMPLOYEE_MASTER" MODIFY ("CONTACT" NOT NULL ENABLE);
  ALTER TABLE "EMPLOYEE_MASTER" MODIFY ("NAME" NOT NULL ENABLE);
