--------------------------------------------------------
--  File created - Tuesday-December-31-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ASSESSMENT_ID
--------------------------------------------------------

   CREATE SEQUENCE  "CHANDAN"."ASSESSMENT_ID"  MINVALUE 1000 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1020 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ASSESSMENT_MASTER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "CHANDAN"."ASSESSMENT_MASTER_SEQ"  MINVALUE 1000 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CANDIDATE_ID
--------------------------------------------------------

   CREATE SEQUENCE  "CHANDAN"."CANDIDATE_ID"  MINVALUE 500 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 520 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CUSTID
--------------------------------------------------------

   CREATE SEQUENCE  "CHANDAN"."CUSTID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 109 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence EMPLOYEE_MASTER_ID
--------------------------------------------------------

   CREATE SEQUENCE  "CHANDAN"."EMPLOYEE_MASTER_ID"  MINVALUE 100 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 120 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence EMPLOYEE_MASTER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "CHANDAN"."EMPLOYEE_MASTER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ORDID
--------------------------------------------------------

   CREATE SEQUENCE  "CHANDAN"."ORDID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 622 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PRODID
--------------------------------------------------------

   CREATE SEQUENCE  "CHANDAN"."PRODID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 200381 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence REQUEST_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "CHANDAN"."REQUEST_SEQUENCE"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ASSESSMENT_MASTER
--------------------------------------------------------

  CREATE TABLE "CHANDAN"."ASSESSMENT_MASTER" 
   (	"ASSESSMENT_ID" NUMBER(10,0), 
	"CANDIDATE_ID" NUMBER(*,0), 
	"HR_ROUND_RATING" NUMBER(10,0), 
	"TECHNICAL_RATING" NUMBER(10,0), 
	"COMMUNICATION_RATING" NUMBER(10,0), 
	"GD_ROUND_RATING" NUMBER(10,0), 
	"APTITUTE_ROUND_RATING" NUMBER(10,0), 
	"OVERALL_ROUND_RATING" NUMBER(10,0), 
	"STATUS" VARCHAR2(30 BYTE), 
	"CREATED_ON" TIMESTAMP (6), 
	"UPDATED_ON" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CANDIDATE_MASTER
--------------------------------------------------------

  CREATE TABLE "CHANDAN"."CANDIDATE_MASTER" 
   (	"CANDIDATE_ID" NUMBER(10,0), 
	"NAME" VARCHAR2(30 BYTE), 
	"LOCATION" VARCHAR2(30 BYTE), 
	"CONTACT" NUMBER(15,0), 
	"EMAIL" VARCHAR2(40 BYTE), 
	"QUALIFICATION" VARCHAR2(40 BYTE), 
	"SKILLS" VARCHAR2(50 BYTE), 
	"CERTIFICATION" VARCHAR2(40 BYTE), 
	"STATUS" VARCHAR2(30 BYTE), 
	"CREATED_ON" TIMESTAMP (6), 
	"UPDATED_ON" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE_MASTER
--------------------------------------------------------

  CREATE TABLE "CHANDAN"."EMPLOYEE_MASTER" 
   (	"EMPLOYEE_ID" NUMBER(*,0), 
	"NAME" VARCHAR2(30 BYTE), 
	"CONTACT" NUMBER(15,0), 
	"DESIGNATION" VARCHAR2(30 BYTE), 
	"QUALIFICATION" VARCHAR2(40 BYTE), 
	"ADDRESS" VARCHAR2(40 BYTE), 
	"EMAIL" VARCHAR2(40 BYTE), 
	"SKILLS" VARCHAR2(50 BYTE), 
	"STATUS" VARCHAR2(30 BYTE), 
	"CREATED_ON" TIMESTAMP (6), 
	"UPDATED_ON" TIMESTAMP (6), 
	"MANAGER_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REQUEST_MASTER
--------------------------------------------------------

  CREATE TABLE "CHANDAN"."REQUEST_MASTER" 
   (	"REQUEST_ID" NUMBER(*,0), 
	"JOB_DESCRIPTION" VARCHAR2(40 BYTE), 
	"REQUIRED_QUALIFICATION" VARCHAR2(40 BYTE), 
	"REQUIRED_SKILLSET" VARCHAR2(40 BYTE), 
	"EXPERIENCE" VARCHAR2(30 BYTE), 
	"RESOURCE_REQUIRED" NUMBER(20,0), 
	"RECRUITED" NUMBER(20,0), 
	"STATUS" VARCHAR2(30 BYTE), 
	"CREATED_ON" TIMESTAMP (6), 
	"UPDATED_ON" TIMESTAMP (6), 
	"RESOURCE_COMMENT" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for View SALES
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "CHANDAN"."SALES" ("REPID", "CUSTID", "CUSTNAME", "PRODID", "PRODNAME", "AMOUNT") AS 
  SELECT REPID, ORD.CUSTID, CUSTOMER.NAME CUSTNAME, PRODUCT.PRODID,
DESCRIP PRODNAME, SUM(ITEMTOT) AMOUNT
FROM ORD, ITEM, CUSTOMER, PRODUCT
WHERE ORD.ORDID = ITEM.ORDID
AND ORD.CUSTID = CUSTOMER.CUSTID
AND ITEM.PRODID = PRODUCT.PRODID
GROUP BY REPID, ORD.CUSTID, NAME, PRODUCT.PRODID, DESCRIP
;
REM INSERTING into CHANDAN.ASSESSMENT_MASTER
SET DEFINE OFF;
Insert into CHANDAN.ASSESSMENT_MASTER (ASSESSMENT_ID,CANDIDATE_ID,HR_ROUND_RATING,TECHNICAL_RATING,COMMUNICATION_RATING,GD_ROUND_RATING,APTITUTE_ROUND_RATING,OVERALL_ROUND_RATING,STATUS,CREATED_ON,UPDATED_ON) values (501,1001,3,5,4,3,4,4,'not selected',to_timestamp('12-FEB-16 11.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('12-JAN-16 05.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into CHANDAN.ASSESSMENT_MASTER (ASSESSMENT_ID,CANDIDATE_ID,HR_ROUND_RATING,TECHNICAL_RATING,COMMUNICATION_RATING,GD_ROUND_RATING,APTITUTE_ROUND_RATING,OVERALL_ROUND_RATING,STATUS,CREATED_ON,UPDATED_ON) values (1000,500,6,5,4,2,2,5,'selected',to_timestamp('12-FEB-16 11.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('12-JAN-16 05.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into CHANDAN.ASSESSMENT_MASTER (ASSESSMENT_ID,CANDIDATE_ID,HR_ROUND_RATING,TECHNICAL_RATING,COMMUNICATION_RATING,GD_ROUND_RATING,APTITUTE_ROUND_RATING,OVERALL_ROUND_RATING,STATUS,CREATED_ON,UPDATED_ON) values (1001,501,5,5,4,4,4,4,'selected',to_timestamp('12-FEB-16 11.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('12-JAN-16 05.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into CHANDAN.ASSESSMENT_MASTER (ASSESSMENT_ID,CANDIDATE_ID,HR_ROUND_RATING,TECHNICAL_RATING,COMMUNICATION_RATING,GD_ROUND_RATING,APTITUTE_ROUND_RATING,OVERALL_ROUND_RATING,STATUS,CREATED_ON,UPDATED_ON) values (1002,502,1,2,2,1,3,5,'not selected',to_timestamp('12-FEB-16 11.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('12-JAN-16 05.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into CHANDAN.ASSESSMENT_MASTER (ASSESSMENT_ID,CANDIDATE_ID,HR_ROUND_RATING,TECHNICAL_RATING,COMMUNICATION_RATING,GD_ROUND_RATING,APTITUTE_ROUND_RATING,OVERALL_ROUND_RATING,STATUS,CREATED_ON,UPDATED_ON) values (1003,503,5,1,2,2,2,4,'not selected',to_timestamp('12-FEB-16 11.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('12-JAN-16 05.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into CHANDAN.ASSESSMENT_MASTER (ASSESSMENT_ID,CANDIDATE_ID,HR_ROUND_RATING,TECHNICAL_RATING,COMMUNICATION_RATING,GD_ROUND_RATING,APTITUTE_ROUND_RATING,OVERALL_ROUND_RATING,STATUS,CREATED_ON,UPDATED_ON) values (1004,504,3,5,5,1,1,4,' not selected',to_timestamp('12-FEB-16 11.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('12-JAN-16 05.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
REM INSERTING into CHANDAN.CANDIDATE_MASTER
SET DEFINE OFF;
Insert into CHANDAN.CANDIDATE_MASTER (CANDIDATE_ID,NAME,LOCATION,CONTACT,EMAIL,QUALIFICATION,SKILLS,CERTIFICATION,STATUS,CREATED_ON,UPDATED_ON) values (1001,'rupesh','mumbai',8898776767,'xyz@gmail.com','BE','.Net','java certified','selected',to_timestamp('12-FEB-16 11.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('12-JAN-16 05.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into CHANDAN.CANDIDATE_MASTER (CANDIDATE_ID,NAME,LOCATION,CONTACT,EMAIL,QUALIFICATION,SKILLS,CERTIFICATION,STATUS,CREATED_ON,UPDATED_ON) values (500,'sweta','mumbai',1234567890,'abc@gmail.com','BE','JAVA','java certified','selected',to_timestamp('15-NOV-19 11.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('15-NOV-19 05.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into CHANDAN.CANDIDATE_MASTER (CANDIDATE_ID,NAME,LOCATION,CONTACT,EMAIL,QUALIFICATION,SKILLS,CERTIFICATION,STATUS,CREATED_ON,UPDATED_ON) values (501,'chandan','thane',1298463740,'xyz@gmail.com','mca','.net','java certified','selected',to_timestamp('12-NOV-19 11.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('12-NOV-19 05.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into CHANDAN.CANDIDATE_MASTER (CANDIDATE_ID,NAME,LOCATION,CONTACT,EMAIL,QUALIFICATION,SKILLS,CERTIFICATION,STATUS,CREATED_ON,UPDATED_ON) values (502,'siddhesh','goa',4653837253,'pqr@gmail.com','be','.java','java certified','selected',to_timestamp('24-NOV-19 11.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('24-NOV-19 05.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into CHANDAN.CANDIDATE_MASTER (CANDIDATE_ID,NAME,LOCATION,CONTACT,EMAIL,QUALIFICATION,SKILLS,CERTIFICATION,STATUS,CREATED_ON,UPDATED_ON) values (503,'vaishnavi','alibaug',1736458974,'vai@gmail.com','be','java','java certified','selected',to_timestamp('12-NOV-19 11.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('12-NOV-19 05.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into CHANDAN.CANDIDATE_MASTER (CANDIDATE_ID,NAME,LOCATION,CONTACT,EMAIL,QUALIFICATION,SKILLS,CERTIFICATION,STATUS,CREATED_ON,UPDATED_ON) values (504,'rupesh','mumbai',8898776767,'xyz@gmail.com','BE','.Net','java certified','selected',to_timestamp('12-FEB-16 11.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('12-JAN-16 05.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
REM INSERTING into CHANDAN.EMPLOYEE_MASTER
SET DEFINE OFF;
Insert into CHANDAN.EMPLOYEE_MASTER (EMPLOYEE_ID,NAME,CONTACT,DESIGNATION,QUALIFICATION,ADDRESS,EMAIL,SKILLS,STATUS,CREATED_ON,UPDATED_ON,MANAGER_ID) values (101,'rupesh',8898713725,'Developer','mca','mumbai','abc@gmail.com','java','selected',to_timestamp('12-FEB-16 11.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('12-JAN-16 05.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),null);
Insert into CHANDAN.EMPLOYEE_MASTER (EMPLOYEE_ID,NAME,CONTACT,DESIGNATION,QUALIFICATION,ADDRESS,EMAIL,SKILLS,STATUS,CREATED_ON,UPDATED_ON,MANAGER_ID) values (102,'rupesh',8898713725,'Developer','mca','mumbai','abc@gmail.com','java','selected',to_timestamp('12-FEB-16 11.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('12-JAN-16 05.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),99);
REM INSERTING into CHANDAN.REQUEST_MASTER
SET DEFINE OFF;
Insert into CHANDAN.REQUEST_MASTER (REQUEST_ID,JOB_DESCRIPTION,REQUIRED_QUALIFICATION,REQUIRED_SKILLSET,EXPERIENCE,RESOURCE_REQUIRED,RECRUITED,STATUS,CREATED_ON,UPDATED_ON,RESOURCE_COMMENT) values (1,'HR','MBA','communication','2year',6,3,'selected',to_timestamp('12-FEB-16 11.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('12-JAN-16 05.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'1 condidate selected');
Insert into CHANDAN.REQUEST_MASTER (REQUEST_ID,JOB_DESCRIPTION,REQUIRED_QUALIFICATION,REQUIRED_SKILLSET,EXPERIENCE,RESOURCE_REQUIRED,RECRUITED,STATUS,CREATED_ON,UPDATED_ON,RESOURCE_COMMENT) values (2,'HR','MBA','communication','2year',6,3,'selected',to_timestamp('12-FEB-16 11.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('12-JAN-16 05.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'2 condidate selected');
Insert into CHANDAN.REQUEST_MASTER (REQUEST_ID,JOB_DESCRIPTION,REQUIRED_QUALIFICATION,REQUIRED_SKILLSET,EXPERIENCE,RESOURCE_REQUIRED,RECRUITED,STATUS,CREATED_ON,UPDATED_ON,RESOURCE_COMMENT) values (3,'TL','masters','communication technical','4year',3,1,'selected',to_timestamp('12-FEB-18 11.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('12-JAN-19 05.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'1 condidate selected');
Insert into CHANDAN.REQUEST_MASTER (REQUEST_ID,JOB_DESCRIPTION,REQUIRED_QUALIFICATION,REQUIRED_SKILLSET,EXPERIENCE,RESOURCE_REQUIRED,RECRUITED,STATUS,CREATED_ON,UPDATED_ON,RESOURCE_COMMENT) values (4,'tester','gradution','technical, communication','3year',4,2,'selected',to_timestamp('12-FEB-13 11.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('12-JAN-18 05.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'1 condidate selected');
Insert into CHANDAN.REQUEST_MASTER (REQUEST_ID,JOB_DESCRIPTION,REQUIRED_QUALIFICATION,REQUIRED_SKILLSET,EXPERIENCE,RESOURCE_REQUIRED,RECRUITED,STATUS,CREATED_ON,UPDATED_ON,RESOURCE_COMMENT) values (5,'Java Developer','gradution','technical,communication','3year',4,2,'selected',to_timestamp('12-FEB-12 11.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('12-JAN-16 05.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'1 condidate selected');
--------------------------------------------------------
--  DDL for Trigger ASSESSMENT_MASTER_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CHANDAN"."ASSESSMENT_MASTER_TRG" 
BEFORE INSERT ON ASSESSMENT_MASTER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ASSESSMENT_ID IS NULL THEN
      SELECT ASSESSMENT_MASTER_SEQ.NEXTVAL INTO :NEW.ASSESSMENT_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "CHANDAN"."ASSESSMENT_MASTER_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger EMPLOYEE_MASTER_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CHANDAN"."EMPLOYEE_MASTER_TRG" 
BEFORE INSERT ON EMPLOYEE_MASTER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.EMPLOYEE_ID IS NULL THEN
      SELECT EMPLOYEE_MASTER_SEQ.NEXTVAL INTO :NEW.EMPLOYEE_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "CHANDAN"."EMPLOYEE_MASTER_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Procedure ADDNEWAUTHOR
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "CHANDAN"."ADDNEWAUTHOR" (
p_id authors.id%type,
P_firstname authors.first_name%type,
p_lastname authors.last_name%type) as
Begin
Insert into authors(id,first_name,last_name)values(p_id,p_firstname,p_lastname);
End addnewauthor

/
--------------------------------------------------------
--  DDL for Procedure ADDNEWBOOK
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "CHANDAN"."ADDNEWBOOK" (
p_isbn in books.isbn%type,
p_category in books.category%type:='oracle server',
p_title in books.title%type,
p_numpages in books.num_pages%type,
p_price in books.price%type,
p_copyright in books.copyright%type default
to_number(to_char(sysdate,'yyyy')),
p_author1 in books.author1%type,
p_author2 in books.author2%type := null,
p_author3 in books.author3%type := null) as


BEGIN
INSERT INTO books (isbn, category, title, num_pages, price, copyright, author1, author2, author3)
VALUES (p_isbn, p_category, p_title, p_numpages, p_price, p_copyright, p_author1, p_author2, p_author3);
END addnewbook;


/
--------------------------------------------------------
--  DDL for Procedure CALLME
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "CHANDAN"."CALLME" (
  paraA varchar2
  ,paraB number,
   paraC boolean,
     paraD Date) as
        begin
        if paraC then
        dbms_output.put_line('paraA='||paraA||'paraB='||paraB||'paraC=true'||'paraD='||paraD);
        else
      dbms_output.put_line('paraA='||paraA||'paraB='||paraB||'paraC=false'||'paraD='||paraD);
      end if;
      end callme;

/
--------------------------------------------------------
--  DDL for Procedure CHD
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "CHANDAN"."CHD" 
AS
v_first_name authors.first_name%TYPE;
v_last_name authors.last_name%TYPE;
v_row_count PLS_INTEGER := 0;

CURSOR auth_cur IS
  SELECT a.first_name, a.last_name, count(b.title)
  FROM authors a, books b
  WHERE a.id = b.author1
  OR a.id = b.author2
  OR a.id = b.author3
  GROUP BY a.first_name, a.last_name
  HAVING count(b.title) > 0
  ORDER BY a.last_name;

BEGIN
OPEN auth_cur;
    LOOP
FETCH auth_cur INTO v_first_name, v_last_name, v_row_count;
EXIT WHEN auth_cur%NOTFOUND;

DBMS_OUTPUT.PUT_LINE(v_last_name||', '||v_first_name||' wrote '||v_row_count||' book(s). ');
END LOOP;
CLOSE auth_cur;

EXCEPTION
WHEN OTHERS
  THEN
  DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;

/
--------------------------------------------------------
--  DDL for Procedure GETEMPDETAILS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "CHANDAN"."GETEMPDETAILS" 
(veno IN number,  vnm OUT varchar, vjb OUT varchar, vsal IN number)
as
  begin
     select ename,job INTO vnm,vjb from emp where empno=veno;
exception
  when no_data_found then
     vnm:=null;
     vjb:=null;
end;

/
--------------------------------------------------------
--  DDL for Function GETNETSAL
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "CHANDAN"."GETNETSAL" (eno in number)
 return number
as
 totsal number;
 begin
   select sal+nvl(comm,0) into totsal from emp
 where empno=eno;
   return totsal;
 exception
  when no_data_found then
return 0;
end;

/
--------------------------------------------------------
--  DDL for Function THREEAUTHORS
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "CHANDAN"."THREEAUTHORS" (p_ISBN IN books.isbn%TYPE)
      RETURN BOOLEAN AS
      v_Author3 books.author3%TYPE;
      BEGIN
      SELECT author3
    INTO v_Author3
    FROM books
    WHERE isbn=p_ISBN;
      If v_Author3 is NULL then
   RETURN FALSE;
     ELSE
   RETURN TRUE;
     END IF;
   END ThreeAuthors;

/
--------------------------------------------------------
--  DDL for Function THREEAUTHORS1
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "CHANDAN"."THREEAUTHORS1" (p_isbn in books.isbn%type)
return boolean as
v_author3 books.author3%type;
begin
select author3
into v_author3 from books where isbn=p_isbn
if v_authors3 is null then
 retrn false;
else
 return true;
end if;
end threeauthors1;

/
--------------------------------------------------------
--  Constraints for Table ASSESSMENT_MASTER
--------------------------------------------------------

  ALTER TABLE "CHANDAN"."ASSESSMENT_MASTER" ADD PRIMARY KEY ("ASSESSMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CHANDAN"."ASSESSMENT_MASTER" MODIFY ("UPDATED_ON" NOT NULL ENABLE);
  ALTER TABLE "CHANDAN"."ASSESSMENT_MASTER" MODIFY ("CREATED_ON" NOT NULL ENABLE);
  ALTER TABLE "CHANDAN"."ASSESSMENT_MASTER" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "CHANDAN"."ASSESSMENT_MASTER" MODIFY ("OVERALL_ROUND_RATING" NOT NULL ENABLE);
  ALTER TABLE "CHANDAN"."ASSESSMENT_MASTER" MODIFY ("APTITUTE_ROUND_RATING" NOT NULL ENABLE);
  ALTER TABLE "CHANDAN"."ASSESSMENT_MASTER" MODIFY ("GD_ROUND_RATING" NOT NULL ENABLE);
  ALTER TABLE "CHANDAN"."ASSESSMENT_MASTER" MODIFY ("COMMUNICATION_RATING" NOT NULL ENABLE);
  ALTER TABLE "CHANDAN"."ASSESSMENT_MASTER" MODIFY ("TECHNICAL_RATING" NOT NULL ENABLE);
  ALTER TABLE "CHANDAN"."ASSESSMENT_MASTER" MODIFY ("HR_ROUND_RATING" NOT NULL ENABLE);
  ALTER TABLE "CHANDAN"."ASSESSMENT_MASTER" MODIFY ("CANDIDATE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REQUEST_MASTER
--------------------------------------------------------

  ALTER TABLE "CHANDAN"."REQUEST_MASTER" ADD PRIMARY KEY ("REQUEST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CHANDAN"."REQUEST_MASTER" MODIFY ("UPDATED_ON" NOT NULL ENABLE);
  ALTER TABLE "CHANDAN"."REQUEST_MASTER" MODIFY ("CREATED_ON" NOT NULL ENABLE);
  ALTER TABLE "CHANDAN"."REQUEST_MASTER" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "CHANDAN"."REQUEST_MASTER" MODIFY ("RECRUITED" NOT NULL ENABLE);
  ALTER TABLE "CHANDAN"."REQUEST_MASTER" MODIFY ("RESOURCE_REQUIRED" NOT NULL ENABLE);
  ALTER TABLE "CHANDAN"."REQUEST_MASTER" MODIFY ("EXPERIENCE" NOT NULL ENABLE);
  ALTER TABLE "CHANDAN"."REQUEST_MASTER" MODIFY ("REQUIRED_SKILLSET" NOT NULL ENABLE);
  ALTER TABLE "CHANDAN"."REQUEST_MASTER" MODIFY ("REQUIRED_QUALIFICATION" NOT NULL ENABLE);
  ALTER TABLE "CHANDAN"."REQUEST_MASTER" MODIFY ("JOB_DESCRIPTION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CANDIDATE_MASTER
--------------------------------------------------------

  ALTER TABLE "CHANDAN"."CANDIDATE_MASTER" ADD PRIMARY KEY ("CANDIDATE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CHANDAN"."CANDIDATE_MASTER" MODIFY ("UPDATED_ON" NOT NULL ENABLE);
  ALTER TABLE "CHANDAN"."CANDIDATE_MASTER" MODIFY ("CREATED_ON" NOT NULL ENABLE);
  ALTER TABLE "CHANDAN"."CANDIDATE_MASTER" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "CHANDAN"."CANDIDATE_MASTER" MODIFY ("CERTIFICATION" NOT NULL ENABLE);
  ALTER TABLE "CHANDAN"."CANDIDATE_MASTER" MODIFY ("SKILLS" NOT NULL ENABLE);
  ALTER TABLE "CHANDAN"."CANDIDATE_MASTER" MODIFY ("QUALIFICATION" NOT NULL ENABLE);
  ALTER TABLE "CHANDAN"."CANDIDATE_MASTER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "CHANDAN"."CANDIDATE_MASTER" MODIFY ("CONTACT" NOT NULL ENABLE);
  ALTER TABLE "CHANDAN"."CANDIDATE_MASTER" MODIFY ("LOCATION" NOT NULL ENABLE);
  ALTER TABLE "CHANDAN"."CANDIDATE_MASTER" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYEE_MASTER
--------------------------------------------------------

  ALTER TABLE "CHANDAN"."EMPLOYEE_MASTER" MODIFY ("UPDATED_ON" NOT NULL ENABLE);
  ALTER TABLE "CHANDAN"."EMPLOYEE_MASTER" MODIFY ("CREATED_ON" NOT NULL ENABLE);
  ALTER TABLE "CHANDAN"."EMPLOYEE_MASTER" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "CHANDAN"."EMPLOYEE_MASTER" MODIFY ("SKILLS" NOT NULL ENABLE);
  ALTER TABLE "CHANDAN"."EMPLOYEE_MASTER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "CHANDAN"."EMPLOYEE_MASTER" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "CHANDAN"."EMPLOYEE_MASTER" MODIFY ("QUALIFICATION" NOT NULL ENABLE);
  ALTER TABLE "CHANDAN"."EMPLOYEE_MASTER" MODIFY ("DESIGNATION" NOT NULL ENABLE);
  ALTER TABLE "CHANDAN"."EMPLOYEE_MASTER" MODIFY ("CONTACT" NOT NULL ENABLE);
  ALTER TABLE "CHANDAN"."EMPLOYEE_MASTER" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ASSESSMENT_MASTER
--------------------------------------------------------

  ALTER TABLE "CHANDAN"."ASSESSMENT_MASTER" ADD FOREIGN KEY ("CANDIDATE_ID")
	  REFERENCES "CHANDAN"."CANDIDATE_MASTER" ("CANDIDATE_ID") ENABLE;
