--------------------------------------------------------
--  File created - Tuesday-December-31-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table REQUEST_MASTER
--------------------------------------------------------

  CREATE TABLE "REQUEST_MASTER" 
   (	"REQUEST_ID" NUMBER(*,0), 
	"JOB_DESCRIPTION" VARCHAR2(40 BYTE), 
	"REQUIRED_QUALIFICATION" VARCHAR2(40 BYTE), 
	"REQUIRED_SKILLSET" VARCHAR2(40 BYTE), 
	"EXPERIENCE" VARCHAR2(30 BYTE), 
	"RESOURCE_REQUIRED" NUMBER(20,0), 
	"RECRUITED" NUMBER(20,0), 
	"STATUS" VARCHAR2(30 BYTE), 
	"CREATED_ON" TIMESTAMP (6), 
	"UPDATED_ON" TIMESTAMP (6), 
	"RESOURCE_COMMENT" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into REQUEST_MASTER
SET DEFINE OFF;
Insert into REQUEST_MASTER (REQUEST_ID,JOB_DESCRIPTION,REQUIRED_QUALIFICATION,REQUIRED_SKILLSET,EXPERIENCE,RESOURCE_REQUIRED,RECRUITED,STATUS,CREATED_ON,UPDATED_ON,RESOURCE_COMMENT) values (1,'HR','MBA','communication','2year',6,3,'selected',to_timestamp('12-FEB-16 11.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('12-JAN-16 05.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'1 condidate selected');
Insert into REQUEST_MASTER (REQUEST_ID,JOB_DESCRIPTION,REQUIRED_QUALIFICATION,REQUIRED_SKILLSET,EXPERIENCE,RESOURCE_REQUIRED,RECRUITED,STATUS,CREATED_ON,UPDATED_ON,RESOURCE_COMMENT) values (2,'HR','MBA','communication','2year',6,3,'selected',to_timestamp('12-FEB-16 11.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('12-JAN-16 05.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'2 condidate selected');
Insert into REQUEST_MASTER (REQUEST_ID,JOB_DESCRIPTION,REQUIRED_QUALIFICATION,REQUIRED_SKILLSET,EXPERIENCE,RESOURCE_REQUIRED,RECRUITED,STATUS,CREATED_ON,UPDATED_ON,RESOURCE_COMMENT) values (3,'TL','masters','communication technical','4year',3,1,'selected',to_timestamp('12-FEB-18 11.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('12-JAN-19 05.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'1 condidate selected');
Insert into REQUEST_MASTER (REQUEST_ID,JOB_DESCRIPTION,REQUIRED_QUALIFICATION,REQUIRED_SKILLSET,EXPERIENCE,RESOURCE_REQUIRED,RECRUITED,STATUS,CREATED_ON,UPDATED_ON,RESOURCE_COMMENT) values (4,'tester','gradution','technical, communication','3year',4,2,'selected',to_timestamp('12-FEB-13 11.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('12-JAN-18 05.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'1 condidate selected');
Insert into REQUEST_MASTER (REQUEST_ID,JOB_DESCRIPTION,REQUIRED_QUALIFICATION,REQUIRED_SKILLSET,EXPERIENCE,RESOURCE_REQUIRED,RECRUITED,STATUS,CREATED_ON,UPDATED_ON,RESOURCE_COMMENT) values (5,'Java Developer','gradution','technical,communication','3year',4,2,'selected',to_timestamp('12-FEB-12 11.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('12-JAN-16 05.12.34.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'1 condidate selected');
--------------------------------------------------------
--  DDL for Index SYS_C007332
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007332" ON "REQUEST_MASTER" ("REQUEST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table REQUEST_MASTER
--------------------------------------------------------

  ALTER TABLE "REQUEST_MASTER" ADD PRIMARY KEY ("REQUEST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "REQUEST_MASTER" MODIFY ("UPDATED_ON" NOT NULL ENABLE);
  ALTER TABLE "REQUEST_MASTER" MODIFY ("CREATED_ON" NOT NULL ENABLE);
  ALTER TABLE "REQUEST_MASTER" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "REQUEST_MASTER" MODIFY ("RECRUITED" NOT NULL ENABLE);
  ALTER TABLE "REQUEST_MASTER" MODIFY ("RESOURCE_REQUIRED" NOT NULL ENABLE);
  ALTER TABLE "REQUEST_MASTER" MODIFY ("EXPERIENCE" NOT NULL ENABLE);
  ALTER TABLE "REQUEST_MASTER" MODIFY ("REQUIRED_SKILLSET" NOT NULL ENABLE);
  ALTER TABLE "REQUEST_MASTER" MODIFY ("REQUIRED_QUALIFICATION" NOT NULL ENABLE);
  ALTER TABLE "REQUEST_MASTER" MODIFY ("JOB_DESCRIPTION" NOT NULL ENABLE);
